import { useEffect, useState } from 'react';
import { ArrowLeftRight, Search, SlidersHorizontal } from 'lucide-react';
import { getLocations, optimizeTrip, type Location, type OptimizeResult } from '../services/api';

export default function Planner({onResults}:{onResults:(r:OptimizeResult,l:Location[],input:Record<string,unknown>)=>void}) {
 const [locations,setLocations]=useState<Location[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const [origin,setOrigin]=useState('HYD_HOME'); const [destination,setDestination]=useState('GOA_CENTER'); const [budget,setBudget]=useState(5000); const [hours,setHours]=useState(18); const [strategy,setStrategy]=useState('smart_balance'); const [sightseeing,setSightseeing]=useState(false); const [modes,setModes]=useState<string[]>([]);
 useEffect(()=>{getLocations().then(d=>setLocations(d.locations)).catch(e=>setError(e.message));},[]);
 const destinationOptions=locations.filter(l=>['destination','railway_station','airport'].includes(l.type));
 const submit=async()=>{setError('');setLoading(true);try{const input={origin,destination,budget,max_duration_hours:hours,strategy,allowed_modes:modes,required_stops:sightseeing?['HUB_HAMPI']:[]};const result=await optimizeTrip(input);onResults(result,locations,input);}catch(e){setError(e instanceof Error?e.message:'Unexpected error');}finally{setLoading(false);}};
 const swap=()=>{setOrigin(destination);setDestination(origin);};
 return <section className="planner-page"><button className="text-button" onClick={()=>window.history.back()}>← Back</button><div className="section-heading left-heading"><span className="eyebrow">YOUR TRIP, YOUR RULES</span><h1>Build your journey</h1><p>We'll compare routes in the configured demo dataset and respect your budget and time limit.</p></div>
 <div className="planner-layout"><div className="form-panel"><div className="panel-heading"><div><h2>Trip details</h2><p>Start with the essentials. Add preferences when you're ready.</p></div><SlidersHorizontal/></div>
 <label>Starting point<select value={origin} onChange={e=>setOrigin(e.target.value)}>{locations.filter(l=>l.type==='origin'||l.type==='railway_station'||l.type==='airport').map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>
 <div className="swap-row"><span className="field-divider"/><button className="swap-button" onClick={swap} title="Swap origin and destination"><ArrowLeftRight size={17}/></button></div>
 <label>Destination<select value={destination} onChange={e=>setDestination(e.target.value)}>{destinationOptions.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>
 <div className="two-fields"><label>Maximum budget (₹)<input type="number" min="1" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label>Maximum duration (hours)<input type="number" min="1" max="168" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label></div>
 <label>Planning strategy<select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="pocket_saver">Pocket Saver — lower cost</option><option value="time_saver">Time Saver — shorter journey</option><option value="smart_balance">Smart Balance — cost + time</option></select></label>
 <label className="check-label"><input type="checkbox" checked={sightseeing} onChange={e=>setSightseeing(e.target.checked)}/><span><b>Include Hampi as a required sightseeing stop</b><small>Only works if the configured route graph has a feasible connection.</small></span></label>
 <details className="advanced"><summary>Transport mode filters</summary><p>Leave all unchecked to allow every mode in the demo dataset.</p><div className="mode-checks">{['Local transport','Taxi','Train','Flight','Bus/Train connection','Train/Bus connection','Bus/local transport','Local taxi/bus'].map(m=><label key={m} className="mini-check"><input type="checkbox" checked={modes.includes(m)} onChange={e=>setModes(old=>e.target.checked?[...old,m]:old.filter(x=>x!==m))}/>{m}</label>)}</div></details>
 {error&&<div className="error-box">{error}</div>}<button className="button button-primary button-large full-button" onClick={submit} disabled={loading||!locations.length||budget<=0||hours<=0}><Search size={18}/>{loading?'Finding feasible routes…':'Find my best routes'}</button><p className="form-disclaimer">Demo data only. This prototype does not access live fares, schedules, or ticket availability.</p>
 </div><aside className="planner-aside"><div className="aside-icon">✦</div><h3>What we'll compare</h3><ul><li>Complete transport and access costs</li><li>Total elapsed journey duration</li><li>Available transport combinations</li><li>Optional or required stops</li><li>Feasible routes within your limits</li></ul><div className="aside-tip"><b>Travel tip</b><p>The cheapest ticket isn't always the cheapest complete journey. Remember to include terminal access and transfers.</p></div></aside></div></section>;
}
